name: On Demand Execution
on: workflow_dispatch
 # schedule:
 #   - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: tech-nl-generic
    steps:
     - uses: actions/checkout@v2
       name: Clone project
    
     - name: Setup Maven
       uses: stCarolas/setup-maven@v4.2
       with:
         maven-version: '3.8.5'
         
     - name: Set up JDK 17
       uses: actions/setup-java@v3.1.1
       with:
         java-version: '17'
         distribution: 'temurin'
         check-latest: true
         cache: maven
        
     - name: run the tests
       env: 
          ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
       run: | 
        mvn clean test "-Dkarate.options=classpath:examples/features/Delete_Despatch_Note.feature" -D userid=${{ secrets.CLIENTID_DN_CA }} -D usersecret=${{ secrets.CLIENTSECRET_DN_CA }} "-Dcred=${{ secrets.REFLEXPASS }}"